services:
  db:
    image: postgres:16
    container_name: unipath-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unipath
    ports:
      - "5432:5432"
    volumes:
      - unipath_pgdata:/var/lib/postgresql/data

volumes:
  unipath_pgdata: