from fastapi import APIRouter,Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import List,Optional
from app.db.database import get_db
from app.models.university_model import University
from app.models.university_model import HistoricalProfile
from app.api.v1.routers.auth import get_current_user
from app.models.user_model import User
from pydantic import BaseModel