"""initial migration

Revision ID: 70964d718f36
Revises: 
Create Date: 2026-08-22 12:31:52.138545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70964d718f36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('tuition', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_country'), 'universities', ['country'], unique=False)
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    op.create_index(op.f('ix_universities_ranking'), 'universities', ['ranking'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('historical_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('university_id', sa.Uuid(), nullable=False),
    sa.Column('program_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('gre_score', sa.Integer(), nullable=True),
    sa.Column('toefl_score', sa.Integer(), nullable=True),
    sa.Column('research_papers', sa.Integer(), nullable=False),
    sa.Column('admitted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_profiles_admitted'), 'historical_profiles', ['admitted'], unique=False)
    op.create_index(op.f('ix_historical_profiles_cgpa'), 'historical_profiles', ['cgpa'], unique=False)
    op.create_index(op.f('ix_historical_profiles_gre_score'), 'historical_profiles', ['gre_score'], unique=False)
    op.create_index(op.f('ix_historical_profiles_id'), 'historical_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_historical_profiles_program_name'), 'historical_profiles', ['program_name'], unique=False)
    op.create_index(op.f('ix_historical_profiles_university_id'), 'historical_profiles', ['university_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_profiles_university_id'), table_name='historical_profiles')
    op.drop_index(op.f('ix_historical_profiles_program_name'), table_name='historical_profiles')
    op.drop_index(op.f('ix_historical_profiles_id'), table_name='historical_profiles')
    op.drop_index(op.f('ix_historical_profiles_gre_score'), table_name='historical_profiles')
    op.drop_index(op.f('ix_historical_profiles_cgpa'), table_name='historical_profiles')
    op.drop_index(op.f('ix_historical_profiles_admitted'), table_name='historical_profiles')
    op.drop_table('historical_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universities_ranking'), table_name='universities')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_country'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
