"""Initial tables

Revision ID: 456b911af986
Revises: 
Create Date: 2026-08-30 19:07:56.943596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '456b911af986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_historicalprofile_id'), table_name='historicalprofile')
    op.drop_index(op.f('ix_historicalprofile_university_id'), table_name='historicalprofile')
    op.drop_table('historicalprofile')
    op.drop_index(op.f('ix_university_id'), table_name='university')
    op.drop_index(op.f('ix_university_name'), table_name='university')
    op.drop_table('university')
    op.drop_index(op.f('ix_evaluation_records_id'), table_name='evaluation_records')
    op.drop_table('evaluation_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('target_country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_program', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gre_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('toefl_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('research_papers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_experience_months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_summary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key_strengths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('areas_for_improvement', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('evaluation_records_pkey'))
    )
    op.create_index(op.f('ix_evaluation_records_id'), 'evaluation_records', ['id'], unique=False)
    op.create_table('university',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ranking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tuition', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('university_pkey'))
    )
    op.create_index(op.f('ix_university_name'), 'university', ['name'], unique=True)
    op.create_index(op.f('ix_university_id'), 'university', ['id'], unique=False)
    op.create_table('historicalprofile',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('university_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('program_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gre_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('toefl_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('research_papers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admitted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], name=op.f('historicalprofile_university_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('historicalprofile_pkey'))
    )
    op.create_index(op.f('ix_historicalprofile_university_id'), 'historicalprofile', ['university_id'], unique=False)
    op.create_index(op.f('ix_historicalprofile_id'), 'historicalprofile', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###
